name: Deploy WordPress Theme

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build, Tag and Publish Theme
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to create releases and tags

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node (required for github-tag-action)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch  # change to 'minor' or 'major' if needed

      - name: Zip the theme
        run: |
          zip -r terminal-theme.zip . -x ".git*" ".github*" "node_modules*" "*.zip"

      - name: Create GitHub Release and attach ZIP
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          files: terminal-theme.zip
